_target_: policy_models.network_modules.DataAugGroup
use_color_jitter: False
use_random_erasing: False
color_jitter:
  brightness: 0.3
  contrast: 0.3
  saturation: 0.3
  hue: 0.05
random_erasing: 
  p: 0.5
  scale: [0.02, 0.05]
  ratio: [0.5, 1.5]
  value: 'random'
