model:
  _target_: policy_models.beacon_multi_view_mask_model.BeaconMultiViewMaskTransformer
  token_dim: 128
  state_dim: 7
  action_dim: 7
  beacon_dim: 6
  num_heads: 4
  num_layers: 2
  sequence_length: ${params.seq_len}
  use_ee: True

use_play: True
mask_type: gt
obs_specs:
  - obs:
      rgb:
        - image_rgb
        - image_ego
      low_dim:
        - image_mask
        - image_ego_mask
        - joint_states
        - ee_states
        - gripper_states
        - beacons
  - obs:
      rgb:
        - image_rgb
      low_dim:
        - beacons

img_size: [200, 200]
mask_size: [200, 200]
img_ego_size: [84, 84]
mask_ego_size: [84, 84]
action_type: 'rel_actions'
separate_channel_mask: False