_target_: policy_models.film_conditioned_model.FilmConditioned
token_dim: 128
action_dim: 8
state_dim: 8
defaults:
  - _self_
  - state_encoder: default
  - static_view_encoder: filmConditioned
  - ego_view_encoder: default
  - transformer_encoder: default
  - action_head: default
  - pos_encoder: default
